repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the ref you want to point at
    hooks:
      - id: black
        language_version: python3.9
        files: (fastvpinns|examples|tests)/.*\.pyi?$|(fastvpinns|examples|tests)/.*\.py$

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=.pylintrc", "--fail-under=6.5", "fastvpinns"]