name: Code Quality Control

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']

jobs:
  quality-check:
    id: quality-check  
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit black pylint

    - name: Run pre-commit
      run: |
        pre-commit run --all-files