name: documentation

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    tags:
      - "*" # any tag

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install distutils
      run: |
        sudo apt-get update

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme myst_parser sphinx_copybutton
        pip install -r requirements.txt

    - name: Make HTML
      run: |
        cd docs
        make html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true