name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit black pylint

    - name: Run pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=6.5 fastvpinns
    
    - name: Run black
      run: |
        black --check fastvpinns
  integration-tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglu1-mesa 
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python3 -m pytest -v tests/integration